### ISSUE TITLE
Wrong description of nclosed in BAGEL manual?

### ISSUE THREAD

**Issue by D16ERG** [qsimulate-open/bagel#230] opened 2021-08-24 11:52 UTC
Dear all,

In the manual page of [CASSCF](https://nubakery.org/multi/casscf.html?highlight=casscf), I am confused by the description of nclosed. nclosed is defined as "Number of electrons / 2". After some testing however; I think this should have been (number of electrons/2)-(number of unsaturations). In the particular case of Benzene for example, this calculation results in ([6*1+6*6]/2)-(3)=18 closed orbitals. For 1,3-cyclohexadiene, a similar calculation results in ([8*1+6*6]/2)-(2)=20 closed orbitals. Does this make sense?

Kind regards,

Didier

**Comment by shiozaki** [comment] 2021-08-24 13:40
Hi Didier,

According to the manual, nclosed is defined as "Number of closed orbitals." with a default value to "Number of electrons / 2". I don't know exactly what you mean by the number of unsaturation but if I interpret that that is the number of electrons in the active orbitals, what you are doing is correct.

There remains a question as to whether the default value is useful, but since it is not a bug I will leave it for now. I am closing this issue.

Best,
Toru

**Closed by shiozaki** 2021-08-24 13:40 UTC
