### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by trex47** [qsimulate-open/bagel#224] opened 2021-04-08 16:11 UTC
When I configure within the obj directory, I get an error saying "mkl.h not found or not working".  I am not sure as to what's wrong here. Please help! Also find attached the config.log file.

[config.log](https://github.com/qsimulate-open/bagel/files/6279969/config.log)

**Comment by shiozaki** [comment] 2021-04-08 16:26
That literally means that mkl.h is not found in the path. Make sure that you have MKL and you sourced the configure file in the bashrc or equivalent.  This is from the log:
```
conftest.c:62:10: fatal error: mkl.h: No such file or directory
   62 | #include <mkl.h>
      |          ^~~~~~~
compilation terminated.
```

You need to do something like 
```
source /opt/intel/bin/compilervars.sh intel64
```
exact command you need to hit is dependent on the MKL installation and whatnots.

Since this is not a bug in bagel, let me close the issue.

**Closed by shiozaki** 2021-04-08 16:26 UTC
